version: '3.8'

services:
  backend:
    build: ./backend
    expose:
      - "8134:8134"
    ports:
      - "8134:8134"

  frontend:
    restart: always
    build: ./frontend
    expose:
      - "5000:5000"
    ports:
      - "5000:5000"

    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8134
