version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - books
      - orders
    environment:
      - BOOKS_URL=http://127.0.0.1:8000
      - ORDERS_URL=http://127.0.0.1:5050
  books:
    build: ./books
    ports:
      - "8000:8000"
  orders:
    build: ./orders
    ports:
      - "5050:5050"
  db:
    image: alpine/sqlite
    volumes:
      - ./my_db.db:/my_db.db